### ISSUE TITLE
Possible XSS attacks via man-in-the-middle attack

### ISSUE THREAD

**Issue by iPaat** [CapCalamity/perfmon#15]
We should not use jQuery's .html() (same for .append(), .prepend(), .before(), .after() etc.) function to insert the JSON response in our DOM. We should use .text() function.

Related: 
https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
http://stackoverflow.com/a/9735118

**Comment by CapCalamity** [comment]
I'll look into it
