### ISSUE TITLE
Network Interface panels show to much information

### ISSUE THREAD

**Issue by CapCalamity** [CapCalamity/perfmon#3]
There are too many columns displayed underneath each interface graph.
They frequently break the layout with very long values

**Comment by CapCalamity** [comment]
Should we split the graphs up into several, smaller graphs?
One for Bytes / Packets / Dropped / Error
That might be a lot of graphs for each interface, and even more with more interfaces,
but it would make handling the values / tooltips a lot easier

Should we drop some information completely? 
Should we drop the graphs except for the Bytes sent/received and include the other info as simple statistics?

**Comment by iPaat** [comment]
I would prefer to have the Bytes sent/received as a graph and the dropped/error information as statistic only.

I think we could drop the packets graph completely or we have a switch where we could switch between packets and byte graph.

**Comment by CapCalamity** [comment]
I like the idea with the switch, I’ll see what i can come up with

**Comment by CapCalamity** [comment]
#14 should fix this

**Comment by SuNflOw1991** [comment]
Fixed with #14.

**Comment by iPaat** [comment]
Fixed with #14.
